# Generated by Django 3.0.7 on 2020-07-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_likedoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mateoffer',
            name='area',
        ),
        migrations.AddField(
            model_name='mateoffer',
            name='location',
            field=models.CharField(default='Grunwaldzki Square', max_length=100),
            preserve_default=False,
        ),
    ]
