# Generated by Django 3.0.7 on 2020-07-09 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api', '0004_auto_20200709_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedoffer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liked_offer', to=settings.AUTH_USER_MODEL),
        ),
    ]
