# Generated by Django 3.0.7 on 2020-07-12 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20200710_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 20, 37, 12, 911011)),
            preserve_default=False,
        ),
    ]
