# Generated by Django 3.0.7 on 2020-08-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_auto_20200713_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='mateoffer',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='RoomPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rest_api.RoomOffer')),
            ],
        ),
    ]
